---
title: "NBA Finals Predictions"
author: "Joshua Smith, Cody Boaz, Sean Sabour"
date: "May 9, 2016"
output: html_document
---

```{r,echo=FALSE}
library(jsonlite)
library(curl)
library(e1071)
library(rpart)
library(rpart.plot)
library(maptree)
source("C:/Users/joshua/Downloads/lin-regr-util.R")

#  source("/Users/seansabour/Desktop/School/CST495 Data Science/Homework/class-util.R")
#  source("/Users/seansabour/Desktop/School/CST495 Data Science/Homework/lin-regr-util.R")
```

#Data Acquisition 
```{r,echo=FALSE}
player = fromJSON("http://stats.nba.com/stats/leaguedashplayerptshot?LeagueID=00&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_playoffs = fromJSON("http://stats.nba.com/stats/leaguedashteamptshot?LeagueID=00&PerMode=Totals&Season=2014-15&SeasonType=Playoffs")

teamstat_playoffs = data.frame(nba_stats_playoffs$resultSets$rowSet[1])
colnames(teamstat_playoffs) <- nba_stats_playoffs$resultSets$headers[[1]]


player_stats = data.frame(player$resultSets$rowSet[1])
colnames(player_stats) <- player$resultSets$headers[[1]]



nba_stats_Hawks = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612737&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Celtics = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612738&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Nets = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612751&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Hornets = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612766&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Bulls = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612741&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Cavaliers = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612739&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Mavericks = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612742&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Nuggets = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612743&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Pistons = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612765&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Warriors = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612744&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Rockets = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612745&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Pacers = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612754&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Clippers = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612746&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Lakers = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612747&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Grizzlies = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612763&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Heat = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612748&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Bucks = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612749&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Timberwolves = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612750&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Pelicans = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612740&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Knicks = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612752&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Thunder = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612760&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Magic = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612753&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_76ers = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612755&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Suns = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612756&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Blazers = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612757&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Kings = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612758&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Spurs = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612759&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Raptors = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612761&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Jazz = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612762&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
nba_stats_Wizards = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612750&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")
# nba_stats3 = fromJSON("http://stats.nba.com/stats/teamgamelog?TeamID=1610612764&PerMode=Totals&Season=2014-15&SeasonType=Regular%20Season")


# putting the data in data frame and adding headers
playerstat_Hawks = data.frame(nba_stats_Hawks$resultSets$rowSet[1])
colnames(playerstat_Hawks) <- nba_stats_Hawks$resultSets$headers[[1]]

playerstat_Celtics = data.frame(nba_stats_Celtics$resultSets$rowSet[1])
colnames(playerstat_Celtics) <- nba_stats_Celtics$resultSets$headers[[1]]

playerstat_Nets = data.frame(nba_stats_Nets$resultSets$rowSet[1])
colnames(playerstat_Nets) <- nba_stats_Nets$resultSets$headers[[1]]

playerstat_Hornets = data.frame(nba_stats_Hornets$resultSets$rowSet[1])
colnames(playerstat_Hornets) <- nba_stats_Hornets$resultSets$headers[[1]]

playerstat_Bulls = data.frame(nba_stats_Bulls$resultSets$rowSet[1])
colnames(playerstat_Bulls) <- nba_stats_Bulls$resultSets$headers[[1]]

playerstat_Cavaliers = data.frame(nba_stats_Cavaliers$resultSets$rowSet[1])
colnames(playerstat_Cavaliers) <- nba_stats_Cavaliers$resultSets$headers[[1]]

playerstat_Mavericks = data.frame(nba_stats_Mavericks$resultSets$rowSet[1])
colnames(playerstat_Mavericks) <- nba_stats_Mavericks$resultSets$headers[[1]]

playerstat_Nuggets = data.frame(nba_stats_Nuggets$resultSets$rowSet[1])
colnames(playerstat_Nuggets) <- nba_stats_Nuggets$resultSets$headers[[1]]

playerstat_Pistons = data.frame(nba_stats_Pistons$resultSets$rowSet[1])
colnames(playerstat_Pistons) <- nba_stats_Pistons$resultSets$headers[[1]]

playerstat_Warriors = data.frame(nba_stats_Warriors$resultSets$rowSet[1])
colnames(playerstat_Warriors) <- nba_stats_Warriors$resultSets$headers[[1]]

playerstat_Rockets = data.frame(nba_stats_Rockets$resultSets$rowSet[1])
colnames(playerstat_Rockets) <- nba_stats_Rockets$resultSets$headers[[1]]

playerstat_Pacers = data.frame(nba_stats_Pacers$resultSets$rowSet[1])
colnames(playerstat_Pacers) <- nba_stats_Pacers$resultSets$headers[[1]]

playerstat_Clippers = data.frame(nba_stats_Clippers$resultSets$rowSet[1])
colnames(playerstat_Clippers) <- nba_stats_Clippers$resultSets$headers[[1]]

playerstat_Lakers = data.frame(nba_stats_Lakers$resultSets$rowSet[1])
colnames(playerstat_Lakers) <- nba_stats_Lakers$resultSets$headers[[1]]

playerstat_Grizzlies = data.frame(nba_stats_Grizzlies$resultSets$rowSet[1])
colnames(playerstat_Grizzlies) <- nba_stats_Grizzlies$resultSets$headers[[1]]

playerstat_Grizzlies = data.frame(nba_stats_Grizzlies$resultSets$rowSet[1])
colnames(playerstat_Grizzlies) <- nba_stats_Grizzlies$resultSets$headers[[1]]

playerstat_Heat = data.frame(nba_stats_Heat$resultSets$rowSet[1])
colnames(playerstat_Heat) <- nba_stats_Heat$resultSets$headers[[1]]

playerstat_Bucks = data.frame(nba_stats_Bucks$resultSets$rowSet[1])
colnames(playerstat_Bucks) <- nba_stats_Bucks$resultSets$headers[[1]]

playerstat_Timberwolves = data.frame(nba_stats_Timberwolves$resultSets$rowSet[1])
colnames(playerstat_Timberwolves) <- nba_stats_Timberwolves$resultSets$headers[[1]]

playerstat_Pelicans = data.frame(nba_stats_Pelicans$resultSets$rowSet[1])
colnames(playerstat_Pelicans) <- nba_stats_Pelicans$resultSets$headers[[1]]

playerstat_Knicks = data.frame(nba_stats_Knicks$resultSets$rowSet[1])
colnames(playerstat_Knicks) <- nba_stats_Knicks$resultSets$headers[[1]]

playerstat_Thunder = data.frame(nba_stats_Thunder$resultSets$rowSet[1])
colnames(playerstat_Thunder) <- nba_stats_Thunder$resultSets$headers[[1]]

playerstat_Magic = data.frame(nba_stats_Magic$resultSets$rowSet[1])
colnames(playerstat_Magic) <- nba_stats_Magic$resultSets$headers[[1]]

playerstat_76ers = data.frame(nba_stats_76ers$resultSets$rowSet[1])
colnames(playerstat_76ers) <- nba_stats_76ers$resultSets$headers[[1]]

playerstat_Suns = data.frame(nba_stats_Suns$resultSets$rowSet[1])
colnames(playerstat_Suns) <- nba_stats_Suns$resultSets$headers[[1]]

playerstat_Blazers = data.frame(nba_stats_Blazers$resultSets$rowSet[1])
colnames(playerstat_Blazers) <- nba_stats_Blazers$resultSets$headers[[1]]

playerstat_Kings = data.frame(nba_stats_Kings$resultSets$rowSet[1])
colnames(playerstat_Kings) <- nba_stats_Kings$resultSets$headers[[1]]

playerstat_Spurs = data.frame(nba_stats_Spurs$resultSets$rowSet[1])
colnames(playerstat_Spurs) <- nba_stats_Spurs$resultSets$headers[[1]]

playerstat_Raptors = data.frame(nba_stats_Raptors$resultSets$rowSet[1])
colnames(playerstat_Raptors) <- nba_stats_Raptors$resultSets$headers[[1]]

playerstat_Jazz = data.frame(nba_stats_Jazz$resultSets$rowSet[1])
colnames(playerstat_Jazz) <- nba_stats_Jazz$resultSets$headers[[1]]

playerstat_Wizards = data.frame(nba_stats_Wizards$resultSets$rowSet[1])
colnames(playerstat_Wizards) <- nba_stats_Wizards$resultSets$headers[[1]]


# Adding team name column
playerstat_Hawks$team_name = "hawks"
playerstat_Celtics$team_name = "celtics"
playerstat_Nets$team_name = "nets"
playerstat_Hornets$team_name = "hornets"
playerstat_Bulls$team_name = "bulls"
playerstat_Cavaliers$team_name = "cavaliers"
playerstat_Mavericks$team_name = "mavericks"
playerstat_Nuggets$team_name = "nuggets"
playerstat_Pistons$team_name = "pistons"
playerstat_Warriors$team_name = "warriors"
playerstat_Rockets$team_name = "rockets"
playerstat_Pacers$team_name = "pacers"
playerstat_Clippers$team_name = "clippers"
playerstat_Lakers$team_name = "lakers"
playerstat_Grizzlies$team_name = "grizzlies"
playerstat_Heat$team_name = "heat"
playerstat_Bucks$team_name = "bucks"
playerstat_Timberwolves$team_name = "timberwolves"
playerstat_Pelicans$team_name = "pelicans"
playerstat_Knicks$team_name = "knicks"
playerstat_Thunder$team_name = "thunder"
playerstat_Magic$team_name = "magic"
playerstat_76ers$team_name = "sixers"
playerstat_Suns$team_name = "suns"
playerstat_Blazers$team_name = "blazers"
playerstat_Kings$team_name = "kings"
playerstat_Spurs$team_name = "spurs"
playerstat_Raptors$team_name = "raptors"
playerstat_Jazz$team_name = "jazz"
playerstat_Wizards$team_name = "wizards"

# 
hawks_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612737&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
celtics_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612738&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
nets_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612751&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
hornets_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612766&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
bulls_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612741&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
cavaliers_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612739&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
mavericks_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612742&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
nuggets_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612743&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
pistons_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612765&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
warriors_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612744&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
rockets_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612745&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
pacers_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612754&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
clippers_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612746&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
lakers_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612747&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
grizzlies_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612763&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
heat_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612748&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
bucks_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612749&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
timberwolves_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612750&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
pelicans_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612740&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
knicks_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612752&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
thunder_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612760&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
magic_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612753&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
sixers_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612755&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
suns_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612756&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
blazers_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612757&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
kings_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612758&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
spurs_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612759&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
raptors_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612761&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
jazz_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612762&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")
wizards_stats = fromJSON("http://stats.nba.com/stats/teamyearbyyearstats?TeamID=1610612764&LeagueId=00&SeasonType=Regular%20Season&perMode=Totals")

# Franchise Stats
Hawks = data.frame(hawks_stats$resultSets$rowSet[1])
colnames(Hawks) <- hawks_stats$resultSets$headers[[1]]

Celtics = data.frame(celtics_stats$resultSets$rowSet[1])
colnames(Celtics) <- celtics_stats$resultSets$headers[[1]]

Nets = data.frame(nets_stats$resultSets$rowSet[1])
colnames(Nets) <- nets_stats$resultSets$headers[[1]]

Hornets = data.frame(hornets_stats$resultSets$rowSet[1])
colnames(Hornets) <- hornets_stats$resultSets$headers[[1]]

Bulls = data.frame(bulls_stats$resultSets$rowSet[1])
colnames(Bulls) <- bulls_stats$resultSets$headers[[1]]

Cavaliers = data.frame(cavaliers_stats$resultSets$rowSet[1])
colnames(Cavaliers) <- cavaliers_stats$resultSets$headers[[1]]

Mavericks = data.frame(mavericks_stats$resultSets$rowSet[1])
colnames(Mavericks) <- mavericks_stats$resultSets$headers[[1]]

Nuggets = data.frame(nuggets_stats$resultSets$rowSet[1])
colnames(Nuggets) <- nuggets_stats$resultSets$headers[[1]]

Pistons = data.frame(pistons_stats$resultSets$rowSet[1])
colnames(Pistons) <- pistons_stats$resultSets$headers[[1]]

Warriors = data.frame(warriors_stats$resultSets$rowSet[1])
colnames(Warriors) <- warriors_stats$resultSets$headers[[1]]

Rockets = data.frame(rockets_stats$resultSets$rowSet[1])
colnames(Rockets) <- rockets_stats$resultSets$headers[[1]]

Pacers = data.frame(pacers_stats$resultSets$rowSet[1])
colnames(Pacers) <- pacers_stats$resultSets$headers[[1]]

Clippers = data.frame(clippers_stats$resultSets$rowSet[1])
colnames(Clippers) <- clippers_stats$resultSets$headers[[1]]

Lakers = data.frame(lakers_stats$resultSets$rowSet[1])
colnames(Lakers) <- lakers_stats$resultSets$headers[[1]]

Grizzlies = data.frame(grizzlies_stats$resultSets$rowSet[1])
colnames(Grizzlies) <- grizzlies_stats$resultSets$headers[[1]]

Heat = data.frame(heat_stats$resultSets$rowSet[1])
colnames(Heat) <- heat_stats$resultSets$headers[[1]]

Bucks = data.frame(bucks_stats$resultSets$rowSet[1])
colnames(Bucks) <- bucks_stats$resultSets$headers[[1]]

Timberwolves = data.frame(timberwolves_stats$resultSets$rowSet[1])
colnames(Timberwolves) <- timberwolves_stats$resultSets$headers[[1]]

Pelicans = data.frame(pelicans_stats$resultSets$rowSet[1])
colnames(Pelicans) <- pelicans_stats$resultSets$headers[[1]]

Knicks = data.frame(knicks_stats$resultSets$rowSet[1])
colnames(Knicks) <- knicks_stats$resultSets$headers[[1]]

Thunder = data.frame(thunder_stats$resultSets$rowSet[1])
colnames(Thunder) <- thunder_stats$resultSets$headers[[1]]

Magic = data.frame(magic_stats$resultSets$rowSet[1])
colnames(Magic) <- magic_stats$resultSets$headers[[1]]

Sixers = data.frame(sixers_stats$resultSets$rowSet[1])
colnames(Sixers) <- sixers_stats$resultSets$headers[[1]]

Suns = data.frame(suns_stats$resultSets$rowSet[1])
colnames(Suns) <- suns_stats$resultSets$headers[[1]]

Blazers = data.frame(blazers_stats$resultSets$rowSet[1])
colnames(Blazers) <- blazers_stats$resultSets$headers[[1]]

Kings = data.frame(kings_stats$resultSets$rowSet[1])
colnames(Kings) <- kings_stats$resultSets$headers[[1]]

Spurs = data.frame(spurs_stats$resultSets$rowSet[1])
colnames(Spurs) <- spurs_stats$resultSets$headers[[1]]

Raptors = data.frame(raptors_stats$resultSets$rowSet[1])
colnames(Raptors) <- raptors_stats$resultSets$headers[[1]]

Jazz = data.frame(jazz_stats$resultSets$rowSet[1])
colnames(Jazz) <- jazz_stats$resultSets$headers[[1]]

Wizards = data.frame(wizards_stats$resultSets$rowSet[1])
colnames(Wizards) <- wizards_stats$resultSets$headers[[1]]

Hawks$NBA_FINALS_APPEARANCE = 4
Celtics$NBA_FINALS_APPEARANCE = 21
Nets$NBA_FINALS_APPEARANCE = 2
Hornets$NBA_FINALS_APPEARANCE = 0
Bulls$NBA_FINALS_APPEARANCE = 6
Cavaliers$NBA_FINALS_APPEARANCE = 2
Mavericks$NBA_FINALS_APPEARANCE = 2
Nuggets$NBA_FINALS_APPEARANCE = 0
Pistons$NBA_FINALS_APPEARANCE = 7
Warriors$NBA_FINALS_APPEARANCE = 7
Rockets$NBA_FINALS_APPEARANCE = 4
Pacers$NBA_FINALS_APPEARANCE = 1
Clippers$NBA_FINALS_APPEARANCE = 0
Lakers$NBA_FINALS_APPEARANCE = 31
Grizzlies$NBA_FINALS_APPEARANCE = 0
Heat$NBA_FINALS_APPEARANCE = 4
Bucks$NBA_FINALS_APPEARANCE = 2
Timberwolves$NBA_FINALS_APPEARANCE = 0
Pelicans$NBA_FINALS_APPEARANCE = 0
Knicks$NBA_FINALS_APPEARANCE = 8
Thunder$NBA_FINALS_APPEARANCE = 1
Magic$NBA_FINALS_APPEARANCE = 2
Sixers$NBA_FINALS_APPEARANCE = 9
Suns$NBA_FINALS_APPEARANCE = 2
Blazers$NBA_FINALS_APPEARANCE = 3
Kings$NBA_FINALS_APPEARANCE = 1
Spurs$NBA_FINALS_APPEARANCE = 6
Raptors$NBA_FINALS_APPEARANCE = 0
Jazz$NBA_FINALS_APPEARANCE = 2
Wizards$NBA_FINALS_APPEARANCE = 4

teams = list( Hawks[Hawks$YEAR == "2015-16", ], Celtics[Celtics$YEAR == "2015-16", ],
              Nets[Nets$YEAR == "2015-16", ], Hornets[Hornets$YEAR == "2015-16", ], 
              Bulls[Bulls$YEAR == "2015-16", ], Cavaliers[Cavaliers$YEAR == "2015-16", ],
              Mavericks[Mavericks$YEAR == "2015-16", ], Nuggets[Nuggets$YEAR == "2015-16", ],
              Pistons[Pistons$YEAR == "2015-16", ], Warriors[Warriors$YEAR == "2015-16", ],
              Rockets[Rockets$YEAR == "2015-16", ], Pacers[Pacers$YEAR == "2015-16", ],
              Clippers[Clippers$YEAR == "2015-16", ], Lakers[Lakers$YEAR == "2015-16", ],
              Grizzlies[Grizzlies$YEAR == "2015-16", ], Heat[Heat$YEAR == "2015-16", ],
              Bucks[Bucks$YEAR == "2015-16", ], Timberwolves[Timberwolves$YEAR == "2015-16", ],
              Pelicans[Pelicans$YEAR == "2015-16", ], Knicks[Knicks$YEAR == "2015-16", ],
              Thunder[Thunder$YEAR == "2015-16", ], Magic[Magic$YEAR == "2015-16", ],
              Sixers[Sixers$YEAR == "2015-16", ], Suns[Suns$YEAR == "2015-16", ],
              Blazers[Blazers$YEAR == "2015-16", ], Kings[Kings$YEAR == "2015-16", ],
              Spurs[Spurs$YEAR == "2015-16", ], Raptors[Raptors$YEAR == "2015-16", ], 
              Jazz[Jazz$YEAR == "2015-16", ], Wizards[Wizards$YEAR == "2015-16", ])



team_season_stats = Reduce(function(...) merge(..., all=TRUE), teams)


```

#Data cleaning
```{r}
# combining the data frames for teams

total_teams = rbind(playerstat_Hawks,
                    playerstat_Celtics,
                    playerstat_Nets,
                    playerstat_Hornets,
                    playerstat_Bulls,
                    playerstat_Cavaliers,
                    playerstat_Mavericks,
                    playerstat_Nuggets,
                    playerstat_Pistons,
                    playerstat_Warriors,
                    playerstat_Rockets,
                    playerstat_Pacers,
                    playerstat_Clippers,
                    playerstat_Lakers,
                    playerstat_Grizzlies,
                    playerstat_Heat,
                    playerstat_Bucks,
                    playerstat_Timberwolves,
                    playerstat_Pelicans,
                    playerstat_Knicks,
                    playerstat_Thunder,
                    playerstat_Magic,
                    playerstat_76ers,
                    playerstat_Suns,
                    playerstat_Blazers,
                    playerstat_Kings,
                    playerstat_Spurs,
                    playerstat_Raptors,
                    playerstat_Jazz,
                    playerstat_Wizards
)

names(total_teams) = tolower(names(total_teams))

#total_teams$away = sample(1, nrow(total_teams), replace = T)

x = grep(pattern= "[@]",total_teams$matchup) 
total_teams$away[x] = 1
total_teams$away[-x] = 0

total_teams$game_date = sort(as.Date(total_teams$game_date,format = "%b %d, %Y"))
total_teams$game_id = as.numeric(levels(total_teams$game_id))[total_teams$game_id]
total_teams$pts = as.numeric(levels(total_teams$pts))[total_teams$pts]
total_teams$fgm = as.numeric(levels(total_teams$fgm))[total_teams$fgm]
total_teams$fg3m = as.numeric(levels(total_teams$fg3m))[total_teams$fg3m]
total_teams$fga = as.numeric(levels(total_teams$fga))[total_teams$fga]
total_teams$fg3a = as.numeric(levels(total_teams$fg3a))[total_teams$fg3a]
total_teams$ftm = as.numeric(levels(total_teams$ftm))[total_teams$ftm]
total_teams$fta = as.numeric(levels(total_teams$fta))[total_teams$fta]
total_teams$oreb = as.numeric(levels(total_teams$oreb))[total_teams$oreb]
total_teams$dreb = as.numeric(levels(total_teams$dreb))[total_teams$dreb]
total_teams$ast = as.numeric(levels(total_teams$ast))[total_teams$ast]
total_teams$stl = as.numeric(levels(total_teams$stl))[total_teams$stl]
total_teams$blk = as.numeric(levels(total_teams$blk))[total_teams$blk]
total_teams$tov = as.numeric(levels(total_teams$tov))[total_teams$tov]
total_teams$fg_pct = as.numeric(levels(total_teams$fg_pct))[total_teams$fg_pct]
total_teams$ft_pct = as.numeric(levels(total_teams$ft_pct))[total_teams$ft_pct]
total_teams$fg3_pct = as.numeric(levels(total_teams$fg3_pct))[total_teams$fg3_pct]
total_teams$pf = as.numeric(levels(total_teams$pf))[total_teams$pf]
total_teams$reb = as.numeric(levels(total_teams$reb))[total_teams$reb]
total_teams$min = as.numeric(levels(total_teams$min))[total_teams$min]


team_season_stats$WIN_PCT =  as.numeric(levels(team_season_stats$WIN_PCT))[team_season_stats$WIN_PCT]
team_season_stats$PTS_RANK =  as.numeric(levels(team_season_stats$PTS_RANK))[team_season_stats$PTS_RANK]
team_season_stats$FG3_PCT =  as.numeric(levels(team_season_stats$FG3_PCT))[team_season_stats$FG3_PCT]
team_season_stats$FG3A =  as.numeric(levels(team_season_stats$FG3A))[team_season_stats$FG3A]
team_season_stats$FG3M =  as.numeric(levels(team_season_stats$FG3M))[team_season_stats$FG3M]
team_season_stats$FG_PCT =  as.numeric(levels(team_season_stats$FG_PCT))[team_season_stats$FG_PCT]
team_season_stats$FGA =  as.numeric(levels(team_season_stats$FGA))[team_season_stats$FTA]
team_season_stats$FGM =  as.numeric(levels(team_season_stats$FGM))[team_season_stats$FTM]
team_season_stats$FT_PCT =  as.numeric(levels(team_season_stats$FT_PCT))[team_season_stats$FT_PCT]
team_season_stats$FTA =  as.numeric(levels(team_season_stats$FTA))[team_season_stats$FTA]
team_season_stats$FTM =  as.numeric(levels(team_season_stats$FTM))[team_season_stats$FTM]
team_season_stats$OREB =  as.numeric(levels(team_season_stats$OREB))[team_season_stats$OREB]
team_season_stats$DREB =  as.numeric(levels(team_season_stats$DREB))[team_season_stats$DREB]
team_season_stats$REB =  as.numeric(levels(team_season_stats$REB))[team_season_stats$REB]
team_season_stats$AST =  as.numeric(levels(team_season_stats$AST))[team_season_stats$AST]
team_season_stats$PF =  as.numeric(levels(team_season_stats$PF))[team_season_stats$PF]
team_season_stats$STL =  as.numeric(levels(team_season_stats$STL))[team_season_stats$STL]
team_season_stats$BLK =  as.numeric(levels(team_season_stats$BLK))[team_season_stats$BLK]
team_season_stats$PTS =  as.numeric(levels(team_season_stats$PTS))[team_season_stats$PTS]


away = total_teams[total_teams$away == 1,]
home = total_teams[total_teams$away == 0,]

home = home[order(home$game_id),]
away = away[order(away$game_id),]

total_teams = cbind(home, away)

```


#Data Exploration
```{r}
## Plot Points Rank vs Win %
par(mfrow=c(1,1))
plot(team_season_stats$PTS_RANK ~ team_season_stats$WIN_PCT,xlim=c(0,1),ylim=c(0,32),col="dodgerblue",pch=16,xlab="Win Ratio",ylab="Points Ranking",main="Points Ranking vs Win Ratio")
text(team_season_stats$PTS_RANK ~ team_season_stats$WIN_PCT ,labels=team_season_stats$TEAM_NAME, cex= 0.5, pos=3)
abline(v=mean(team_season_stats$WIN_PCT))

##PLOTS Finals Appearances vs Current Win %
plot(team_season_stats$NBA_FINALS_APPEARANCE ~ team_season_stats$WIN_PCT,xlim=c(0,1),ylim=c(0,32),col="dodgerblue",pch=16,xlab="Win Ratio",ylab="Finals Appearances",main="Finals Appearances vs. Current Win Ratio")
text(team_season_stats$NBA_FINALS_APPEARANCE ~ team_season_stats$WIN_PCT,labels=team_season_stats$TEAM_NAME, cex= 0.5, pos=3)

plot(~ away  + fgm + stl + blk + ast + fg3_pct + fg3a + fg3m, data = total_teams)
plot(total_teams$fg_pct ~ total_teams$team_id, col=c("firebrick"))
plot(total_teams$fg3_pct ~ total_teams$team_id, col=c("firebrick"), las=2)
plot(total_teams$pf ~ total_teams$team_id, col=c("firebrick"), las=2)
plot(total_teams$pts ~ total_teams$team_id, col=c("firebrick"), las=2)
plot(total_teams$fg3m ~ total_teams$fg3_pct, col=c("firebrick", "blue"), pch=16)
plot(total_teams$fgm ~ total_teams$ast, col=c("firebrick", "blue"), pch=16)
plot(total_teams$fgm, total_teams$ast, col=c("firebrick", "blue"), pch=16)
plot(total_teams$fg3a ~ total_teams$fg3m, col=c("firebrick", "blue"), pch=16)

# 3 Pointers Attempted vs 3 Pointers Made KOBEEEE
plot(team_season_stats$FG3M ~ team_season_stats$FG3A, col=c("dodgerblue"),ylim=c(400,1150),main="3 Pointers Attempted vs. 3 Pointers Made",pch=16,xlab="FGM",ylab="FGA")
text(team_season_stats$FG3M ~ team_season_stats$FG3A,labels=team_season_stats$TEAM_NAME, cex= 0.5, pos=3)


# Free Throws Attempted vs Free Throws Made SHAQ Baby
plot(team_season_stats$FTM ~ team_season_stats$FTA, col=c("dodgerblue"),ylim=c(min(team_season_stats$FTM),max(team_season_stats$FTM)),main="FT Attempted vs. FT Made",pch=16,xlab="FTM",ylab="FTA")
text(team_season_stats$FTM ~ team_season_stats$FTA,labels=team_season_stats$TEAM_NAME, cex= 0.5, pos=3)

# Field Goals Attempted vs Field Goals Made
plot(team_season_stats$FGA ~ team_season_stats$FGM, col=c("dodgerblue"),ylim=c(6200,7400),main="FG Attempted vs. FG Made",pch=16,xlab="FGM",ylab="FGA")
text(team_season_stats$FGA ~ team_season_stats$FGM,labels=team_season_stats$TEAM_NAME, cex= 0.5, pos=3)

```


#Spliting Data Into  Training and Test
```{r}
# set.seed(132)
split = split_data(total_teams)
tr_data = split[[1]]
te_data = split[[2]]
```


#Linear Model
```{r}


fit3 = lm(pts ~ fgm + oreb + dreb + reb + ast + stl + tov + pf, data = tr_data)
summary(fit3)


fit = lm(pts ~ fgm  + ftm , data = tr_data)
summary(fit)
 
predicted = predict(fit, newdata = te_data)
actual = te_data$pts
plot_predict_actual(predicted, actual, 10, "Predictions from test data")


# fv = c("away","fgm","fga","fg3m","fg3a","ftm","fta","oreb","dreb","ast","stl","blk","tov")

#fit = lm(pts ~ fg_pct + tov, data = tr_data)


# summary(fit2)
```

#Predictions and Analysis
```{r}
# x = te_data[te_data$game_id == 0021400916,]
# predicted = predict(fit, newdata = x)


predicted = predict(fit, newdata = te_data)
# predicted2 = predict(fit3, newdata = te_data)

rmse = sqrt(mean((te_data$pts - predicted)^2))
# rmse2 = sqrt(mean((te_data$pts - predicted2)^2))

rmse
# rmse2

```


# LINEAR MODEL WINNER
```{r}
head_to_head = function(team1,team2){
  # get both the team's entire season stats
#   firstTeam = total_teams[total_teams$team_name == team1,]
#   secondTeam = total_teams[total_teams$team_name == team2,]
#   
#   firstTeam$game_date = sort(as.Date(firstTeam$game_date,format = "%b %d, %Y"))
#   secondTeam$game_date = sort(as.Date(secondTeam$game_date,format = "%b %d, %Y"))

  
  firstTeam = te_data[te_data$team_name == team1,]
  last_10_games_team1 = tail(firstTeam,10)
  last_10_games_team1$away = as.numeric(last_10_games_team1$away)
  
  # Calculates home court advantage likelihood of winning
  home_advantage = sum(last_10_games_team1$wl == 1 & last_10_games_team1$away == 0) / sum(last_10_games_team1$away == 0)
  
  last_10_games_team1 = lapply(last_10_games_team1[, c("pf", "reb", "fgm", "fga", "fg_pct", "fg3m", "fg3a", "fg3_pct", "ftm",  "fta", "ft_pct", "oreb", "dreb", "ast", "stl", "blk", "tov", "pts","away")], mean, na.rm = TRUE)
  
  
  secondTeam = te_data[te_data$team_name == team2,]
  last_10_games_team2 = tail(secondTeam,10)
  last_10_games_team2$away = as.numeric(last_10_games_team2$away)
  
  # Calculates home court advantage likelihood of winning
  home_advantage2 = sum(last_10_games_team2$wl == 1 & last_10_games_team2$away == 0) / sum(last_10_games_team2$away == 0)

  last_10_games_team2 = lapply(last_10_games_team2[, c("pf", "reb", "fgm", "fga", "fg_pct", "fg3m", "fg3a", "fg3_pct", "ftm",  "fta", "ft_pct", "oreb", "dreb", "ast", "stl", "blk", "tov", "pts","away")], mean, na.rm = TRUE)
  
  
  # Predicts and rounds the scores
  score1 = round(predict(fit, newdata = last_10_games_team1))
  score2 = round(predict(fit, newdata = last_10_games_team2))
  
  final_results = data.frame(score=c(score1,score2))
  final_results$win[1] = ifelse(final_results$score[1] > final_results$score[2],"W","L")
  final_results$win[2] = ifelse(final_results$score[2] > final_results$score[1],"W","L")

  return(final_results)
}

head_to_head("pistons","clippers")

par(mfrow=c(2,1))
plot_predict_actual(predicted ,te_data$pts, 5, title = "Predictions from Testing Data")
# plot_predict_actual(predicted2 ,te_data$pts, 5, title = "Predictions from Testing Data2")
```

# Logistic regression
```{r}


te_data$wl = ifelse(te_data$wl == "W", 1, 0 )
tr_data$wl = ifelse(tr_data$wl == "W", 1, 0 )



# this fit works better than the latter
fit3 = glm(wl ~ fta + reb + ast + stl + blk + tov, data = tr_data, family = binomial)


# fit3 = glm(wl ~ pts + away  + fgm + stl + blk + ast + fg3_pct + fg3a + fg3m, data = tr_data, family = binomial)

head(tr_data)
summary(fit3)

# compute confusion matrix
y = predict(fit3, newdata=te_data, type="response")
predicts3 = as.numeric(y > 0.5)
actuals3 = te_data$wl
conf_mtx3 = table(predicts3, actuals3)

par(mfrow=c(1,1))
print(conf_mtx3)
plot(conf_mtx3, col="firebrick")

succ_rate3 = mean(actuals3 == predicts3)

par(mfrow=c(1,2))
hist(y[actuals3 == 0], main="Output when loss game", 
     breaks=10, xlim=c(0,1), ylim=c(0,15), col="red4", xlab="model predictions")
hist(y[actuals3 == 1], main="Output when won game", 
     breaks=10, xlim=c(0,1), ylim=c(0,15), col="red4", xlab="model predictions")
```

#Prec_recall summary
```{r}
prec_recall_summary = function(predicts, actuals) {
  thresh = seq(0, 1, length.out=50)
  prec_rec = data.frame()
  actuals = factor(as.numeric(actuals))
  for (th in thresh) {
    predicts = factor(as.numeric(y >= th), levels=c("0","1"))
    prec_rec = rbind(prec_rec, as.vector(table(predicts, actuals)))
  }
  names(prec_rec) = c("TN", "FP", "FN", "TP")
  prec_rec$threshold = thresh
  prec_rec$precision = prec_rec$TP/(prec_rec$TP + prec_rec$FP)
  prec_rec$recall    = prec_rec$TP/(prec_rec$TP + prec_rec$FN)
  prec_rec$false_pos = prec_rec$FP/(prec_rec$FP + prec_rec$TN)
  return(prec_rec)
}

prec_rec1 = prec_recall_summary(predicts3, actuals3)

par(mfrow=c(2,1))
par(mar=c(4, 4, 2, 0.5))

plot(prec_rec1$precision ~ prec_rec1$threshold, type = "l", col="blue", xlab="Threshold", ylab="Presiction")
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted",
     lwd = par("lwd"), equilogs = TRUE)
plot(prec_rec1$recall ~ prec_rec1$threshold, type = "l", col = "red", xlab="Threshold", ylab="Recall")
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted",
     lwd = par("lwd"), equilogs = TRUE)


par(mfrow=c(1,1))
plot(prec_rec1$recall ~ prec_rec1$false_pos, type = "l", col = "red", xlab="Threshold", ylab="Recall")
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted",
     lwd = par("lwd"), equilogs = TRUE)

title("receiver operating characteristic")

par(mfrow=c(1,1))
plot(prec_rec1$precision ~ prec_rec1$recall, type = "l", col = "red", xlab="precision", ylab="recall")
grid(nx = NULL, ny = NULL, col = "lightgray", lty = "dotted",
     lwd = par("lwd"), equilogs = TRUE)
title("Precision recall curve")


# function get feactures team1 is the primary team, team 2 is against
get_feactures_v = function(team1, team2, total_teams){

  # getting the total games a team has played agaist each other
  x = total_teams[total_teams$matchup == paste(team1, "@", team2) | total_teams$matchup == paste(team1, "vs.", team2),]
team_dat = x[sample(1:nrow(x), 50, replace = T),]

x1 = grep(pattern= paste0(team2) ,total_teams$matchup) 
x1 = total_teams[x1,]

against_team = x1[sample(1:nrow(x1), 10, replace = T),]

x = rbind(team_dat, against_team)

# tail(x, 50)

x = lapply(team_dat[, c("pf", "reb", "fgm", "fga", "fg_pct", "fg3m", "fg3a", "fg3_pct", "ftm",  "fta", "ft_pct", "oreb", "dreb", "ast", "stl", "blk", "tov", "pts")], mean, na.rm = TRUE)

y = head(team_dat, 1)


y$fgm = round(x$fgm)
y$fga = round(x$fga)
y$fg_pct = x$fg_pct
y$fg3m = round(x$fg3m)
y$fg3a = round(x$fg3a)
y$fg3_pct = x$fg3_pct
y$ftm = round(x$ftm)
y$fta = round(x$fta)
y$ft_pct = x$ft_pct
y$oreb = round(x$oreb)
y$dreb = round(x$dreb)
y$reb = round(x$reb)
y$ast = round(x$ast)
y$stl = round(x$stl)
y$blk = round(x$blk)
y$tov = round(x$tov)
y$pts = round(x$pts)
y$pf = round(x$pf)
y$reb = round(x$reb)

y$wl = ifelse(y$wl == "W", 1, 0 )
y$team_id = 0
y$game_id = 0
y$game_date = 0

y$matchup = as.character(y$matchup)

y$matchup = paste(team1, "vs.", team2)

return(y)
}


# this method plays the games for each team. The features need to be fixed. read error message when running.
play_games = function(team1, team2, total_teams, fit_r, fit_l){
team1_w = NULL
team2_w = NULL
team1_s = NULL
team2_s = NULL



  for(i in 1:7)
  {
     x = get_feactures_v(team1, team2, total_teams)
     y = get_feactures_v(team2, team1, total_teams)
  
     # when these teams play team one score is predicted 
     predicted4 = predict(fit_r, newdata = x)
     predicted5 = predict(fit_r, newdata = y)
     
      predicted6 = predict(fit_l, newdata=x, type="response")
      predicts6 = as.numeric(predicted6 > 0.5)
      
      predicted7 = predict(fit_l, newdata=y, type="response")
      predicts7 = as.numeric(predicted7 > 0.5)   
    
      if(predicted4 >  predicted5){
        predicts6 = 1
        predicts7 = 0
      }
      else{
        predicts6 = 0
        predicts7 = 1
      }
      
    team1_w = c(team1_w, predicts6)
    team2_w = c(team2_w, predicts7)
  
    team1_s = c(team1_s, predicted4)
     team2_s = c(team2_s, predicted5)
     
#      print(team1_w)
#      print(team2_w)
      if(sum(team1_w) == 4 | sum(team2_w) == 4){
        break
      }
  }

   team1_w = sum(team1_w)
   team2_w = sum(team2_w)
  
  print(team1_w)
  print(team2_w)
  print(team1_s)
  print(team2_s)

}
total_teams$wl = ifelse(total_teams$wl == "W", 1, 0)
# perameter one is team, 2 agaist, 3 regresstion, 4 list ligistic model

play_games("OKC", "DAL", total_teams, fit, fit3)

```
